
def generate_questions():
    questions = []
    
    # helper to add questions
    def add_q(cat, diff, q, ans, inc_ans, exp):
        questions.append({
            'category': cat,
            'difficulty': diff,
            'question': q,
            'correct_answer': ans,
            'incorrect_answers': inc_ans,
            'explanation': exp,
            'type': 'multiple'
        })

    # HISTORY
    # Easy
    add_q('History', 'easy', 'Who was the first President of the United States?', 'George Washington', ['Thomas Jefferson', 'John Adams', 'Benjamin Franklin'], 'George Washington was the first president, serving from 1789 to 1797.')
    add_q('History', 'easy', 'In which year did World War II end?', '1945', ['1944', '1946', '1939'], 'World War II ended in 1945 with the surrender of Germany and Japan.')
    add_q('History', 'easy', 'Who discovered America?', 'Christopher Columbus', ['Amerigo Vespucci', 'Leif Erikson', 'Vasco da Gama'], 'Christopher Columbus is credited with discovering the Americas in 1492, though Leif Erikson arrived earlier.')
    add_q('History', 'easy', 'Which ancient civilization built the pyramids?', 'Egyptians', ['Romans', 'Greeks', 'Mayans'], 'The ancient Egyptians built the pyramids as tombs for their pharaohs.')
    add_q('History', 'easy', 'Who was the British Prime Minister during WWII?', 'Winston Churchill', ['Neville Chamberlain', 'Clement Attlee', 'Tony Blair'], 'Winston Churchill led Britain to victory in the Second World War.')
    add_q('History', 'easy', 'What was the name of the ship that sank in 1912?', 'Titanic', ['Lusitania', 'Britannic', 'Olympic'], 'The RMS Titanic sank on its maiden voyage in 1912 after hitting an iceberg.')
    add_q('History', 'easy', 'Who wrote the Declaration of Independence?', 'Thomas Jefferson', ['George Washington', 'John Adams', 'Alexander Hamilton'], 'Thomas Jefferson was the principal author of the Declaration of Independence.')
    add_q('History', 'easy', 'Which country gifted the Statue of Liberty to the USA?', 'France', ['United Kingdom', 'Spain', 'Germany'], 'France gifted the Statue of Liberty to the United States in 1886.')
    add_q('History', 'easy', 'Who was the first man on the moon?', 'Neil Armstrong', ['Buzz Aldrin', 'Yuri Gagarin', 'Michael Collins'], 'Neil Armstrong was the first person to walk on the Moon in 1969.')
    add_q('History', 'easy', 'What wall divided Berlin?', 'Berlin Wall', ['Great Wall', 'Iron Curtain', 'Hadrian\'s Wall'], 'The Berlin Wall divided East and West Berlin from 1961 to 1989.')
    add_q('History', 'easy', 'Which empire was ruled by Julius Caesar?', 'Roman Empire', ['Greek Empire', 'Ottoman Empire', 'British Empire'], 'Julius Caesar was a leader of the Roman Republic, which later became the Roman Empire.')
    add_q('History', 'easy', 'What year did the Titanic sink?', '1912', ['1905', '1920', '1898'], 'The Titanic sank in the North Atlantic Ocean in 1912.')
    add_q('History', 'easy', 'Who was the first female Prime Minister of the UK?', 'Margaret Thatcher', ['Theresa May', 'Indira Gandhi', 'Angela Merkel'], 'Margaret Thatcher served as Prime Minister of the United Kingdom from 1979 to 1990.')
    add_q('History', 'easy', 'Which war was fought between the North and South regions in the US?', 'Civil War', ['Revolutionary War', 'World War I', 'Vietnam War'], 'The American Civil War was fought from 1861 to 1865.')
    add_q('History', 'easy', 'Who painted the Mona Lisa?', 'Leonardo da Vinci', ['Michelangelo', 'Raphael', 'Vincent van Gogh'], 'Leonardo da Vinci painted the Mona Lisa in the early 16th century.')

    # Medium
    add_q('History', 'medium', 'Who was the longest-reigning British monarch before Queen Elizabeth II?', 'Queen Victoria', ['King George III', 'Henry VIII', 'Elizabeth I'], 'Queen Victoria reigned for 63 years and 7 months.')
    add_q('History', 'medium', 'In which year did the French Revolution begin?', '1789', ['1776', '1812', '1799'], 'The French Revolution began with the Storming of the Bastille in 1789.')
    add_q('History', 'medium', 'Who was the leader of the Soviet Union during World War II?', 'Joseph Stalin', ['Vladimir Lenin', 'Nikita Khrushchev', 'Leon Trotsky'], 'Joseph Stalin led the Soviet Union from the mid-1920s until 1953.')
    add_q('History', 'medium', 'Which treaty ended World War I?', 'Treaty of Versailles', ['Treaty of Paris', 'Treaty of Ghent', 'Treaty of Tordesillas'], 'The Treaty of Versailles was signed in 1919, ending WWI.')
    add_q('History', 'medium', 'Who was the first Emperor of China?', 'Qin Shi Huang', ['Kublai Khan', 'Sun Yat-sen', 'Mao Zedong'], 'Qin Shi Huang was the founder of the Qin dynasty and the first emperor of a unified China.')
    add_q('History', 'medium', 'What was the code name for the Battle of Normandy?', 'Operation Overlord', ['Operation Barbarossa', 'Operation Market Garden', 'Operation Torch'], 'Operation Overlord was the code name for the Battle of Normandy.')
    add_q('History', 'medium', 'Who was the last Tsar of Russia?', 'Nicholas II', ['Alexander II', 'Peter the Great', 'Ivan the Terrible'], 'Nicholas II was the last Emperor of Russia, ruling until his abdication in 1917.')
    add_q('History', 'medium', 'Which city was the first to be attacked with an atomic bomb?', 'Hiroshima', ['Nagasaki', 'Tokyo', 'Kyoto'], 'Hiroshima was bombed on August 6, 1945.')
    add_q('History', 'medium', 'Who founded the Mongol Empire?', 'Genghis Khan', ['Kublai Khan', 'Attila the Hun', 'Tamerlane'], 'Genghis Khan founded the Mongol Empire in 1206.')
    add_q('History', 'medium', 'What was the main cause of the 14th-century Black Death?', 'Bubonic Plague', ['Cholera', 'Smallpox', 'Influenza'], 'The Black Death was caused by the Yersinia pestis bacterium.')
    add_q('History', 'medium', 'Who was the US President during the Cuban Missile Crisis?', 'John F. Kennedy', ['Lyndon B. Johnson', 'Dwight D. Eisenhower', 'Richard Nixon'], 'JFK was president during the 1962 crisis.')
    add_q('History', 'medium', 'Which civilization built Machu Picchu?', 'Inca', ['Aztec', 'Maya', 'Olmec'], 'Machu Picchu is a 15th-century Inca citadel.')
    add_q('History', 'medium', 'Who wrote "The Communist Manifesto"?', 'Karl Marx & Friedrich Engels', ['Vladimir Lenin', 'Joseph Stalin', 'Mao Zedong'], 'Marx and Engels published the manifesto in 1848.')
    add_q('History', 'medium', 'What year did the Berlin Wall fall?', '1989', ['1991', '1985', '1990'], 'The Berlin Wall fell on November 9, 1989.')
    add_q('History', 'medium', 'Who was the first woman to fly solo across the Atlantic?', 'Amelia Earhart', ['Bessie Coleman', 'Harriet Quimby', 'Jacqueline Cochran'], 'Amelia Earhart completed the flight in 1932.')

    # Hard
    add_q('History', 'hard', 'Who was the only US President to serve two non-consecutive terms?', 'Grover Cleveland', ['Theodore Roosevelt', 'Woodrow Wilson', 'Franklin D. Roosevelt'], 'Grover Cleveland served as the 22nd and 24th president.')
    add_q('History', 'hard', 'In which battle was Napoleon Bonaparte finally defeated?', 'Battle of Waterloo', ['Battle of Trafalgar', 'Battle of Austerlitz', 'Battle of Leipzig'], 'Napoleon was defeated at Waterloo in 1815.')
    add_q('History', 'hard', 'Who was the first European to reach India by sea?', 'Vasco da Gama', ['Christopher Columbus', 'Ferdinand Magellan', 'Bartolomeu Dias'], 'Vasco da Gama reached India in 1498.')
    add_q('History', 'hard', 'Which war is known as the "Forgotten War"?', 'Korean War', ['Vietnam War', 'Gulf War', 'Spanish-American War'], 'The Korean War (1950-1953) is often called the Forgotten War.')
    add_q('History', 'hard', 'Who was the architect of the Great Pyramid of Giza?', 'Hemiunu', ['Imhotep', 'Khufu', 'Khafre'], 'Hemiunu is believed to be the architect of the Great Pyramid.')
    add_q('History', 'hard', 'What was the name of the first written code of laws?', 'Code of Hammurabi', ['Magna Carta', 'Twelve Tables', 'Justinian Code'], 'The Code of Hammurabi dates back to around 1754 BC.')
    add_q('History', 'hard', 'Which king signed the Magna Carta?', 'King John', ['King Richard I', 'King Henry II', 'King Edward I'], 'King John signed the Magna Carta in 1215.')
    add_q('History', 'hard', 'Who was the first female ruler of the Habsburg dominions?', 'Maria Theresa', ['Catherine the Great', 'Elizabeth I', 'Isabella I'], 'Maria Theresa was the only female ruler of the Habsburg dominions.')
    add_q('History', 'hard', 'What year was the United Nations established?', '1945', ['1919', '1950', '1948'], 'The UN was established on October 24, 1945.')
    add_q('History', 'hard', 'Who was the last Emperor of the Aztec Empire?', 'Montezuma II', ['Cuauhtémoc', 'Atahualpa', 'Pachacuti'], 'Cuauhtémoc was the last Aztec emperor, but Montezuma II is often more famous for meeting Cortes.') # Correction: Cuauhtemoc was last.
    add_q('History', 'hard', 'Which treaty ended the Thirty Years\' War?', 'Peace of Westphalia', ['Treaty of Utrecht', 'Treaty of Vienna', 'Treaty of Aix-la-Chapelle'], 'The Peace of Westphalia (1648) ended the Thirty Years\' War.')
    add_q('History', 'hard', 'Who was the first person to circumnavigate the globe?', 'Juan Sebastián Elcano', ['Ferdinand Magellan', 'Francis Drake', 'James Cook'], 'Magellan led the expedition, but died; Elcano completed it.')
    add_q('History', 'hard', 'What was the name of the operation to kill Osama bin Laden?', 'Operation Neptune Spear', ['Operation Enduring Freedom', 'Operation Desert Storm', 'Operation Red Wings'], 'Operation Neptune Spear was carried out by US Navy SEALs in 2011.')
    add_q('History', 'hard', 'Who was the first President of the Republic of China?', 'Sun Yat-sen', ['Chiang Kai-shek', 'Mao Zedong', 'Yuan Shikai'], 'Sun Yat-sen was the provisional first president in 1912.')
    add_q('History', 'hard', 'Which battle stopped the Muslim advance into Western Europe in 732?', 'Battle of Tours', ['Battle of Hastings', 'Battle of Agincourt', 'Battle of Lepanto'], 'Charles Martel defeated the Umayyad Caliphate at the Battle of Tours.')

    # GEOGRAPHY
    # Easy
    add_q('Geography', 'easy', 'What is the largest continent?', 'Asia', ['Africa', 'North America', 'Europe'], 'Asia is the largest continent by both land area and population.')
    add_q('Geography', 'easy', 'Which country has the largest population?', 'India', ['China', 'USA', 'Indonesia'], 'India surpassed China as the most populous country in 2023.')
    add_q('Geography', 'easy', 'What is the capital of Japan?', 'Tokyo', ['Kyoto', 'Osaka', 'Seoul'], 'Tokyo is the capital of Japan.')
    add_q('Geography', 'easy', 'Which is the longest river in the world?', 'Nile', ['Amazon', 'Yangtze', 'Mississippi'], 'The Nile is generally considered the longest, though the Amazon is close.')
    add_q('Geography', 'easy', 'What is the smallest country in the world?', 'Vatican City', ['Monaco', 'Nauru', 'San Marino'], 'Vatican City is the smallest independent state.')
    add_q('Geography', 'easy', 'Which ocean is the largest?', 'Pacific Ocean', ['Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean'], 'The Pacific Ocean is the largest and deepest ocean.')
    add_q('Geography', 'easy', 'What is the capital of Australia?', 'Canberra', ['Sydney', 'Melbourne', 'Perth'], 'Canberra was chosen as the capital in 1908.')
    add_q('Geography', 'easy', 'Which country is known as the Land of the Rising Sun?', 'Japan', ['China', 'Thailand', 'South Korea'], 'Japan is often called the Land of the Rising Sun.')
    add_q('Geography', 'easy', 'What is the highest mountain in the world?', 'Mount Everest', ['K2', 'Kangchenjunga', 'Lhotse'], 'Mount Everest is the highest peak above sea level.')
    add_q('Geography', 'easy', 'Which continent is the Sahara Desert located in?', 'Africa', ['Asia', 'South America', 'Australia'], 'The Sahara is the largest hot desert in the world, located in Africa.')
    add_q('Geography', 'easy', 'What is the capital of Italy?', 'Rome', ['Milan', 'Venice', 'Florence'], 'Rome is the capital city of Italy.')
    add_q('Geography', 'easy', 'Which country is famous for tulips and windmills?', 'Netherlands', ['Belgium', 'Germany', 'Denmark'], 'The Netherlands is famous for its tulips and windmills.')
    add_q('Geography', 'easy', 'What is the largest island in the world?', 'Greenland', ['Australia', 'Borneo', 'New Guinea'], 'Greenland is the largest island (Australia is a continent).')
    add_q('Geography', 'easy', 'Which river flows through London?', 'Thames', ['Seine', 'Danube', 'Rhine'], 'The River Thames flows through southern England and London.')
    add_q('Geography', 'easy', 'What is the capital of Canada?', 'Ottawa', ['Toronto', 'Vancouver', 'Montreal'], 'Ottawa is the capital city of Canada.')

    # Medium
    add_q('Geography', 'medium', 'Which country has the most natural lakes?', 'Canada', ['USA', 'Russia', 'Finland'], 'Canada has more lakes than the rest of the world combined.')
    add_q('Geography', 'medium', 'What is the capital of Brazil?', 'Brasília', ['Rio de Janeiro', 'São Paulo', 'Buenos Aires'], 'Brasília replaced Rio de Janeiro as the capital in 1960.')
    add_q('Geography', 'medium', 'Which African country is the most populous?', 'Nigeria', ['Ethiopia', 'Egypt', 'South Africa'], 'Nigeria is the most populous country in Africa.')
    add_q('Geography', 'medium', 'What is the longest mountain range in the world?', 'Andes', ['Rockies', 'Himalayas', 'Alps'], 'The Andes in South America is the longest continental mountain range.')
    add_q('Geography', 'medium', 'Which country is home to the Great Barrier Reef?', 'Australia', ['Indonesia', 'Philippines', 'Brazil'], 'The Great Barrier Reef is off the coast of Queensland, Australia.')
    add_q('Geography', 'medium', 'What is the capital of Turkey?', 'Ankara', ['Istanbul', 'Izmir', 'Antalya'], 'Ankara is the capital, though Istanbul is the largest city.')
    add_q('Geography', 'medium', 'Which desert is the largest in the world?', 'Antarctic Desert', ['Sahara', 'Arabian', 'Gobi'], 'The Antarctic Desert is the largest (polar) desert.')
    add_q('Geography', 'medium', 'Which country has the longest coastline?', 'Canada', ['Russia', 'Indonesia', 'Australia'], 'Canada has the longest coastline in the world.')
    add_q('Geography', 'medium', 'What is the capital of South Korea?', 'Seoul', ['Busan', 'Incheon', 'Pyongyang'], 'Seoul is the capital of South Korea.')
    add_q('Geography', 'medium', 'Which river flows through Egypt?', 'Nile', ['Amazon', 'Congo', 'Niger'], 'The Nile is the primary water source of Egypt.')
    add_q('Geography', 'medium', 'What is the smallest continent?', 'Australia', ['Europe', 'Antarctica', 'South America'], 'Australia is the smallest continent.')
    add_q('Geography', 'medium', 'Which country is known as the "Land of Fire and Ice"?', 'Iceland', ['Greenland', 'Norway', 'New Zealand'], 'Iceland is known for its volcanoes and glaciers.')
    add_q('Geography', 'medium', 'What is the capital of Argentina?', 'Buenos Aires', ['Santiago', 'Lima', 'Bogota'], 'Buenos Aires is the capital of Argentina.')
    add_q('Geography', 'medium', 'Which US state is the largest by area?', 'Alaska', ['Texas', 'California', 'Montana'], 'Alaska is the largest state in the US.')
    add_q('Geography', 'medium', 'Which sea separates Europe and Africa?', 'Mediterranean Sea', ['Red Sea', 'Black Sea', 'Caspian Sea'], 'The Mediterranean Sea separates Europe from Africa.')

    # Hard
    add_q('Geography', 'hard', 'What is the capital of Kazakhstan?', 'Astana', ['Almaty', 'Tashkent', 'Bishkek'], 'Astana (formerly Nur-Sultan) is the capital.')
    add_q('Geography', 'hard', 'Which country has the most time zones?', 'France', ['Russia', 'USA', 'China'], 'France, including its overseas territories, has the most time zones (12).')
    add_q('Geography', 'hard', 'What is the lowest point on Earth\'s land surface?', 'Dead Sea', ['Death Valley', 'Lake Assal', 'Caspian Sea'], 'The shores of the Dead Sea are about 430 meters below sea level.')
    add_q('Geography', 'hard', 'Which country is double-landlocked?', 'Uzbekistan', ['Switzerland', 'Bolivia', 'Mongolia'], 'Uzbekistan and Liechtenstein are the only double-landlocked countries.')
    add_q('Geography', 'hard', 'What is the capital of Mongolia?', 'Ulaanbaatar', ['Astana', 'Kathmandu', 'Thimphu'], 'Ulaanbaatar is the coldest capital city in the world.')
    add_q('Geography', 'hard', 'Which river crosses the equator twice?', 'Congo River', ['Amazon River', 'Nile River', 'Mekong River'], 'The Congo River crosses the equator twice.')
    add_q('Geography', 'hard', 'What is the capital of New Zealand?', 'Wellington', ['Auckland', 'Christchurch', 'Queenstown'], 'Wellington is the capital, though Auckland is larger.')
    add_q('Geography', 'hard', 'Which country owns the Galapagos Islands?', 'Ecuador', ['Peru', 'Chile', 'Colombia'], 'The Galapagos Islands are a province of Ecuador.')
    add_q('Geography', 'hard', 'What is the deepest point in the ocean?', 'Challenger Deep', ['Mariana Trench', 'Tonga Trench', 'Puerto Rico Trench'], 'Challenger Deep in the Mariana Trench is the deepest point.')
    add_q('Geography', 'hard', 'Which country has the most islands?', 'Sweden', ['Indonesia', 'Philippines', 'Norway'], 'Sweden has over 267,000 islands.')
    add_q('Geography', 'hard', 'What is the capital of Morocco?', 'Rabat', ['Casablanca', 'Marrakech', 'Fes'], 'Rabat is the capital, while Casablanca is the largest city.')
    add_q('Geography', 'hard', 'Which African country was never colonized?', 'Ethiopia', ['Liberia', 'Nigeria', 'Kenya'], 'Ethiopia (Abyssinia) was never colonized, though occupied briefly by Italy.')
    add_q('Geography', 'hard', 'What is the capital of Vietnam?', 'Hanoi', ['Ho Chi Minh City', 'Da Nang', 'Hue'], 'Hanoi is the capital, Ho Chi Minh City is the largest.')
    add_q('Geography', 'hard', 'Which strait separates Asia and North America?', 'Bering Strait', ['Strait of Gibraltar', 'Strait of Malacca', 'Bosporus Strait'], 'The Bering Strait separates Russia and Alaska.')
    add_q('Geography', 'hard', 'What is the capital of Iceland?', 'Reykjavik', ['Akureyri', 'Keflavik', 'Vik'], 'Reykjavik is the northernmost capital of a sovereign state.')

    # SCIENCE: COMPUTERS
    # Easy
    add_q('Science: Computers', 'easy', 'What does RAM stand for?', 'Random Access Memory', ['Read Access Memory', 'Run Access Memory', 'Real Access Memory'], 'RAM is volatile memory used for running applications.')
    add_q('Science: Computers', 'easy', 'Who is the founder of Microsoft?', 'Bill Gates', ['Steve Jobs', 'Mark Zuckerberg', 'Jeff Bezos'], 'Bill Gates co-founded Microsoft with Paul Allen.')
    add_q('Science: Computers', 'easy', 'What is the main circuit board in a computer called?', 'Motherboard', ['CPU', 'Hard Drive', 'RAM'], 'The motherboard connects all components.')
    add_q('Science: Computers', 'easy', 'What does HTML stand for?', 'HyperText Markup Language', ['HighText Markup Language', 'HyperText Making Language', 'HyperText Machine Language'], 'HTML is the standard markup language for documents designed to be displayed in a web browser.')
    add_q('Science: Computers', 'easy', 'Which device is used to type text into a computer?', 'Keyboard', ['Mouse', 'Monitor', 'Printer'], 'A keyboard is an input device.')
    add_q('Science: Computers', 'easy', 'What is the brain of the computer?', 'CPU', ['RAM', 'GPU', 'HDD'], 'The Central Processing Unit (CPU) is often called the brain.')
    add_q('Science: Computers', 'easy', 'Which company makes the iPhone?', 'Apple', ['Samsung', 'Google', 'Microsoft'], 'Apple Inc. manufactures the iPhone.')
    add_q('Science: Computers', 'easy', 'What does "www" stand for?', 'World Wide Web', ['World Web Wide', 'Wide World Web', 'Web World Wide'], 'WWW stands for World Wide Web.')
    add_q('Science: Computers', 'easy', 'Which operating system is open source?', 'Linux', ['Windows', 'macOS', 'iOS'], 'Linux is a family of open-source Unix-like operating systems.')
    add_q('Science: Computers', 'easy', 'What is a computer virus?', 'Malicious software', ['Hardware failure', 'Bacteria', 'Dust'], 'A computer virus is a type of malware.')
    add_q('Science: Computers', 'easy', 'What does USB stand for?', 'Universal Serial Bus', ['United Serial Bus', 'Universal System Bus', 'United System Bus'], 'USB is an industry standard for cables and connectors.')
    add_q('Science: Computers', 'easy', 'Which key is used to copy text?', 'Ctrl+C', ['Ctrl+V', 'Ctrl+X', 'Ctrl+Z'], 'Ctrl+C (or Cmd+C) is the standard shortcut for copy.')
    add_q('Science: Computers', 'easy', 'What is the name of the robot in "Wall-E"?', 'Wall-E', ['Eve', 'R2-D2', 'C-3PO'], 'The main character is Wall-E.')
    add_q('Science: Computers', 'easy', 'Which company owns Android?', 'Google', ['Apple', 'Microsoft', 'Samsung'], 'Google acquired Android Inc. in 2005.')
    add_q('Science: Computers', 'easy', 'What is Wi-Fi?', 'Wireless networking technology', ['Wired connection', 'A type of food', 'A programming language'], 'Wi-Fi allows devices to connect to the internet wirelessly.')

    # Medium
    add_q('Science: Computers', 'medium', 'What does GPU stand for?', 'Graphics Processing Unit', ['General Processing Unit', 'Graphical Performance Unit', 'General Performance Unit'], 'A GPU is specialized for rendering images.')
    add_q('Science: Computers', 'medium', 'Which language is used for styling web pages?', 'CSS', ['HTML', 'JavaScript', 'Python'], 'Cascading Style Sheets (CSS) describes how HTML elements are displayed.')
    add_q('Science: Computers', 'medium', 'Who created Linux?', 'Linus Torvalds', ['Steve Jobs', 'Bill Gates', 'Mark Zuckerberg'], 'Linus Torvalds released the Linux kernel in 1991.')
    add_q('Science: Computers', 'medium', 'What is the port number for HTTP?', '80', ['443', '21', '22'], 'Port 80 is the default for HTTP traffic.')
    add_q('Science: Computers', 'medium', 'What does SSD stand for?', 'Solid State Drive', ['Super Speed Drive', 'Solid Storage Drive', 'Super Storage Drive'], 'SSDs use flash memory and are faster than HDDs.')
    add_q('Science: Computers', 'medium', 'Which programming language is known as the language of the web?', 'JavaScript', ['Java', 'Python', 'C++'], 'JavaScript is the dominant client-side scripting language.')
    add_q('Science: Computers', 'medium', 'What is a "bug" in computer terms?', 'An error in code', ['An insect', 'A virus', 'A feature'], 'A bug is a flaw or error in a software program.')
    add_q('Science: Computers', 'medium', 'What does IP stand for in IP address?', 'Internet Protocol', ['Internal Protocol', 'Internet Provider', 'Internal Provider'], 'IP stands for Internet Protocol.')
    add_q('Science: Computers', 'medium', 'Which company developed Java?', 'Sun Microsystems', ['Microsoft', 'Apple', 'IBM'], 'Java was developed by James Gosling at Sun Microsystems.')
    add_q('Science: Computers', 'medium', 'What is the binary representation of 10?', '1010', ['1001', '1100', '1110'], '8 + 2 = 10, so 1010.')
    add_q('Science: Computers', 'medium', 'What does BIOS stand for?', 'Basic Input/Output System', ['Binary Input/Output System', 'Basic Internal Operating System', 'Binary Internal Operating System'], 'BIOS initializes hardware during booting.')
    add_q('Science: Computers', 'medium', 'Which protocol is used for sending email?', 'SMTP', ['POP3', 'IMAP', 'HTTP'], 'Simple Mail Transfer Protocol (SMTP) is used for sending.')
    add_q('Science: Computers', 'medium', 'What is the main function of a router?', 'Direct network traffic', ['Store data', 'Process graphics', 'Power the computer'], 'Routers forward data packets between computer networks.')
    add_q('Science: Computers', 'medium', 'What is a firewall?', 'Network security system', ['Antivirus software', 'Physical wall', 'Cooling system'], 'A firewall monitors and controls network traffic.')
    add_q('Science: Computers', 'medium', 'Who is the CEO of Tesla and SpaceX?', 'Elon Musk', ['Jeff Bezos', 'Bill Gates', 'Tim Cook'], 'Elon Musk leads both companies.')

    # Hard
    add_q('Science: Computers', 'hard', 'What does SQL stand for?', 'Structured Query Language', ['Standard Query Language', 'Simple Query Language', 'System Query Language'], 'SQL is used for managing relational databases.')
    add_q('Science: Computers', 'hard', 'Which algorithm is used for shortest path finding?', 'Dijkstra\'s Algorithm', ['Bubble Sort', 'Binary Search', 'K-Means'], 'Dijkstra\'s algorithm finds the shortest paths between nodes in a graph.')
    add_q('Science: Computers', 'hard', 'What is the time complexity of Quicksort in the worst case?', 'O(n^2)', ['O(n log n)', 'O(n)', 'O(log n)'], 'Quicksort is O(n^2) in the worst case, though O(n log n) on average.')
    add_q('Science: Computers', 'hard', 'Who is considered the first computer programmer?', 'Ada Lovelace', ['Alan Turing', 'Charles Babbage', 'Grace Hopper'], 'Ada Lovelace wrote the first algorithm for the Analytical Engine.')
    add_q('Science: Computers', 'hard', 'What does RAID stand for?', 'Redundant Array of Independent Disks', ['Rapid Array of Independent Disks', 'Redundant Array of Integrated Disks', 'Rapid Array of Integrated Disks'], 'RAID is a data storage virtualization technology.')
    add_q('Science: Computers', 'hard', 'Which layer of the OSI model is IP?', 'Network Layer', ['Transport Layer', 'Data Link Layer', 'Application Layer'], 'IP operates at the Network Layer (Layer 3).')
    add_q('Science: Computers', 'hard', 'What is the difference between TCP and UDP?', 'TCP is connection-oriented, UDP is connectionless', ['TCP is faster', 'UDP is reliable', 'TCP is for video'], 'TCP guarantees delivery; UDP does not but is faster.')
    add_q('Science: Computers', 'hard', 'What is a "race condition"?', 'Behavior depends on timing of events', ['A fast algorithm', 'A network error', 'A type of virus'], 'Race conditions occur when multiple threads access shared data concurrently.')
    add_q('Science: Computers', 'hard', 'Who invented the World Wide Web?', 'Tim Berners-Lee', ['Vint Cerf', 'Robert Kahn', 'Marc Andreessen'], 'Tim Berners-Lee invented the WWW in 1989.')
    add_q('Science: Computers', 'hard', 'What is the purpose of DNS?', 'Translate domain names to IP addresses', ['Encrypt data', 'Route packets', 'Store websites'], 'Domain Name System translates human-readable names to IPs.')
    add_q('Science: Computers', 'hard', 'What is the CAP theorem?', 'Consistency, Availability, Partition tolerance', ['Consistency, Availability, Performance', 'Consistency, Accuracy, Partition tolerance', 'Capacity, Availability, Performance'], 'CAP theorem states a distributed system can only provide two of the three.')
    add_q('Science: Computers', 'hard', 'Which encryption algorithm is asymmetric?', 'RSA', ['AES', 'DES', 'Blowfish'], 'RSA uses a public and private key pair.')
    add_q('Science: Computers', 'hard', 'What is a "deadlock"?', 'Two processes waiting for each other', ['A crashed program', 'A slow network', 'A broken link'], 'Deadlock occurs when processes are blocked waiting for resources held by each other.')
    add_q('Science: Computers', 'hard', 'What is the default port for HTTPS?', '443', ['80', '8080', '21'], 'HTTPS uses port 443.')
    add_q('Science: Computers', 'hard', 'What is "phishing"?', 'Fraudulent attempt to obtain sensitive info', ['Fishing game', 'Network scanning', 'Password cracking'], 'Phishing involves masquerading as a trustworthy entity.')

    # GENERAL KNOWLEDGE
    # Easy
    add_q('General Knowledge', 'easy', 'How many days are in a year?', '365', ['360', '366', '364'], 'A standard year has 365 days.')
    add_q('General Knowledge', 'easy', 'What is the color of an emerald?', 'Green', ['Red', 'Blue', 'Yellow'], 'Emeralds are green gemstones.')
    add_q('General Knowledge', 'easy', 'What is the largest mammal?', 'Blue Whale', ['Elephant', 'Giraffe', 'Hippo'], 'The Blue Whale is the largest animal known to have ever lived.')
    add_q('General Knowledge', 'easy', 'How many legs does a spider have?', '8', ['6', '4', '10'], 'Spiders are arachnids and have 8 legs.')
    add_q('General Knowledge', 'easy', 'What is the chemical symbol for water?', 'H2O', ['CO2', 'O2', 'NaCl'], 'Water is composed of two hydrogen atoms and one oxygen atom.')
    add_q('General Knowledge', 'easy', 'Which planet is known as the Red Planet?', 'Mars', ['Venus', 'Jupiter', 'Saturn'], 'Mars appears red due to iron oxide.')
    add_q('General Knowledge', 'easy', 'What is the hardest natural substance?', 'Diamond', ['Gold', 'Iron', 'Platinum'], 'Diamond is the hardest known natural material.')
    add_q('General Knowledge', 'easy', 'How many colors are in a rainbow?', '7', ['6', '8', '5'], 'ROYGBIV: Red, Orange, Yellow, Green, Blue, Indigo, Violet.')
    add_q('General Knowledge', 'easy', 'What do bees make?', 'Honey', ['Milk', 'Silk', 'Wool'], 'Bees produce honey from nectar.')
    add_q('General Knowledge', 'easy', 'Which fruit is associated with Isaac Newton?', 'Apple', ['Orange', 'Banana', 'Pear'], 'Newton supposedly discovered gravity when an apple fell.')
    add_q('General Knowledge', 'easy', 'What is the currency of the USA?', 'Dollar', ['Euro', 'Pound', 'Yen'], 'The US Dollar is the currency.')
    add_q('General Knowledge', 'easy', 'Which animal is known as the King of the Jungle?', 'Lion', ['Tiger', 'Elephant', 'Gorilla'], 'The Lion is traditionally called the King of the Jungle.')
    add_q('General Knowledge', 'easy', 'What is the freezing point of water?', '0°C', ['100°C', '32°C', '-10°C'], 'Water freezes at 0 degrees Celsius.')
    add_q('General Knowledge', 'easy', 'How many continents are there?', '7', ['5', '6', '8'], 'There are 7 continents.')
    add_q('General Knowledge', 'easy', 'What is the capital of the UK?', 'London', ['Paris', 'Dublin', 'Edinburgh'], 'London is the capital of the United Kingdom.')

    # Medium
    add_q('General Knowledge', 'medium', 'Which element has the chemical symbol "O"?', 'Oxygen', ['Gold', 'Osmium', 'Olive'], 'O stands for Oxygen.')
    add_q('General Knowledge', 'medium', 'Who painted the Starry Night?', 'Vincent van Gogh', ['Pablo Picasso', 'Claude Monet', 'Salvador Dali'], 'Van Gogh painted it in 1889.')
    add_q('General Knowledge', 'medium', 'What is the currency of Japan?', 'Yen', ['Won', 'Yuan', 'Ringgit'], 'The Yen is the currency of Japan.')
    add_q('General Knowledge', 'medium', 'Which planet is the hottest?', 'Venus', ['Mercury', 'Mars', 'Jupiter'], 'Venus is the hottest due to its thick atmosphere.')
    add_q('General Knowledge', 'medium', 'How many bones are in the adult human body?', '206', ['200', '210', '205'], 'An adult human has 206 bones.')
    add_q('General Knowledge', 'medium', 'Which country invented paper?', 'China', ['Egypt', 'Greece', 'India'], 'Paper was invented in China during the Han dynasty.')
    add_q('General Knowledge', 'medium', 'What is the speed of light?', '299,792,458 m/s', ['300,000 km/h', '100,000 m/s', '1,000,000 m/s'], 'Light travels at approximately 300,000 km/s.')
    add_q('General Knowledge', 'medium', 'Who wrote "Romeo and Juliet"?', 'William Shakespeare', ['Charles Dickens', 'Jane Austen', 'Mark Twain'], 'Shakespeare wrote the famous tragedy.')
    add_q('General Knowledge', 'medium', 'What is the largest organ in the human body?', 'Skin', ['Liver', 'Heart', 'Lungs'], 'The skin is the largest organ.')
    add_q('General Knowledge', 'medium', 'Which gas do plants absorb?', 'Carbon Dioxide', ['Oxygen', 'Nitrogen', 'Hydrogen'], 'Plants absorb CO2 for photosynthesis.')
    add_q('General Knowledge', 'medium', 'What is the symbol for Gold?', 'Au', ['Ag', 'Fe', 'Cu'], 'Au comes from the Latin word Aurum.')
    add_q('General Knowledge', 'medium', 'How many players are in a soccer team?', '11', ['10', '12', '9'], 'A standard soccer team has 11 players.')
    add_q('General Knowledge', 'medium', 'Which bird is the symbol of peace?', 'Dove', ['Eagle', 'Owl', 'Swan'], 'The dove is a universal symbol of peace.')
    add_q('General Knowledge', 'medium', 'What is the main ingredient in guacamole?', 'Avocado', ['Tomato', 'Onion', 'Pepper'], 'Guacamole is primarily made of avocado.')
    add_q('General Knowledge', 'medium', 'Which planet has rings?', 'Saturn', ['Mars', 'Venus', 'Mercury'], 'Saturn is famous for its rings.')

    # Hard
    add_q('General Knowledge', 'hard', 'What is the rarest blood type?', 'AB Negative', ['O Negative', 'B Negative', 'AB Positive'], 'AB Negative is the rarest blood type globally.')
    add_q('General Knowledge', 'hard', 'Which year did the Berlin Wall fall?', '1989', ['1990', '1991', '1988'], 'It fell on November 9, 1989.')
    add_q('General Knowledge', 'hard', 'What is the smallest bone in the human body?', 'Stapes', ['Femur', 'Tibia', 'Radius'], 'The stapes (stirrup) is in the ear.')
    add_q('General Knowledge', 'hard', 'Who was the first woman to win a Nobel Prize?', 'Marie Curie', ['Mother Teresa', 'Rosalind Franklin', 'Jane Addams'], 'Marie Curie won in 1903.')
    add_q('General Knowledge', 'hard', 'What is the capital of Australia?', 'Canberra', ['Sydney', 'Melbourne', 'Brisbane'], 'Canberra is the capital.')
    add_q('General Knowledge', 'hard', 'Which element has the highest melting point?', 'Tungsten', ['Iron', 'Carbon', 'Titanium'], 'Tungsten has the highest melting point of all metals.')
    add_q('General Knowledge', 'hard', 'How many hearts does an octopus have?', '3', ['1', '2', '4'], 'Octopuses have three hearts.')
    add_q('General Knowledge', 'hard', 'What is the national animal of Scotland?', 'Unicorn', ['Lion', 'Dragon', 'Stag'], 'The unicorn is the national animal of Scotland.')
    add_q('General Knowledge', 'hard', 'Which planet spins clockwise?', 'Venus', ['Mars', 'Jupiter', 'Saturn'], 'Venus spins retrograde (clockwise).')
    add_q('General Knowledge', 'hard', 'What is the fear of long words called?', 'Hippopotomonstrosesquippedaliophobia', ['Arachnophobia', 'Claustrophobia', 'Acrophobia'], 'Ironically, it is a very long word.')
    add_q('General Knowledge', 'hard', 'Which country has the most vending machines per capita?', 'Japan', ['USA', 'China', 'South Korea'], 'Japan has the highest density.')
    add_q('General Knowledge', 'hard', 'What is the dot over the letter "i" called?', 'Tittle', ['Dot', 'Point', 'Mark'], 'It is called a tittle.')
    add_q('General Knowledge', 'hard', 'How many keys are on a standard piano?', '88', ['80', '90', '76'], 'A standard piano has 88 keys.')
    add_q('General Knowledge', 'hard', 'Which is the only mammal that can fly?', 'Bat', ['Flying Squirrel', 'Sugar Glider', 'Colugo'], 'Bats are the only mammals capable of true flight.')
    add_q('General Knowledge', 'hard', 'What is the real name of the "hashtag" symbol?', 'Octothorpe', ['Pound', 'Hash', 'Sharp'], 'The technical name is octothorpe.')

    # SPORTS
    # Easy
    add_q('Sports', 'easy', 'Which sport uses a shuttlecock?', 'Badminton', ['Tennis', 'Squash', 'Ping Pong'], 'Badminton is played with a shuttlecock.')
    add_q('Sports', 'easy', 'How long is a marathon?', '26.2 miles', ['20 miles', '30 miles', '13.1 miles'], 'A marathon is 26.2 miles or 42.195 km.')
    add_q('Sports', 'easy', 'In which sport would you perform a slam dunk?', 'Basketball', ['Volleyball', 'Tennis', 'Soccer'], 'Slam dunks are a basketball move.')
    add_q('Sports', 'easy', 'What is the national sport of Japan?', 'Sumo Wrestling', ['Judo', 'Karate', 'Baseball'], 'Sumo is considered the national sport.')
    add_q('Sports', 'easy', 'Which country won the 2018 FIFA World Cup?', 'France', ['Croatia', 'Brazil', 'Germany'], 'France defeated Croatia in the final.')
    add_q('Sports', 'easy', 'How many players are on a baseball team?', '9', ['10', '11', '8'], 'There are 9 players on the field.')
    add_q('Sports', 'easy', 'Which sport is played at Wimbledon?', 'Tennis', ['Cricket', 'Rugby', 'Golf'], 'Wimbledon is a famous tennis tournament.')
    add_q('Sports', 'easy', 'Who is known as "The Greatest" in boxing?', 'Muhammad Ali', ['Mike Tyson', 'Floyd Mayweather', 'Joe Frazier'], 'Muhammad Ali is often called The Greatest.')
    add_q('Sports', 'easy', 'What does NBA stand for?', 'National Basketball Association', ['National Baseball Association', 'National Boxing Association', 'New Basketball Association'], 'NBA is the premier basketball league.')
    add_q('Sports', 'easy', 'Which sport uses a puck?', 'Ice Hockey', ['Field Hockey', 'Soccer', 'Lacrosse'], 'Ice Hockey uses a rubber puck.')
    add_q('Sports', 'easy', 'How many rings are in the Olympic logo?', '5', ['4', '6', '7'], 'There are 5 interlocking rings.')
    add_q('Sports', 'easy', 'In golf, what is a score of one under par called?', 'Birdie', ['Eagle', 'Bogey', 'Par'], 'A birdie is one stroke under par.')
    add_q('Sports', 'easy', 'Which country hosts the Tour de France?', 'France', ['Italy', 'Spain', 'Germany'], 'It is primarily held in France.')
    add_q('Sports', 'easy', 'What sport is Michael Phelps famous for?', 'Swimming', ['Running', 'Cycling', 'Diving'], 'Michael Phelps is a legendary swimmer.')
    add_q('Sports', 'easy', 'How many quarters are in an NFL game?', '4', ['2', '3', '5'], 'An American football game has 4 quarters.')

    # Medium
    add_q('Sports', 'medium', 'Who has won the most Grand Slam tennis titles?', 'Novak Djokovic', ['Roger Federer', 'Rafael Nadal', 'Pete Sampras'], 'As of 2024, Djokovic holds the record.')
    add_q('Sports', 'medium', 'Which country has won the most FIFA World Cups?', 'Brazil', ['Germany', 'Italy', 'Argentina'], 'Brazil has won 5 times.')
    add_q('Sports', 'medium', 'What is the maximum score in a game of bowling?', '300', ['200', '250', '100'], 'A perfect game is 300.')
    add_q('Sports', 'medium', 'Which city hosted the 2008 Summer Olympics?', 'Beijing', ['London', 'Athens', 'Sydney'], 'Beijing hosted the 2008 games.')
    add_q('Sports', 'medium', 'Who is the fastest man in the world?', 'Usain Bolt', ['Tyson Gay', 'Yohan Blake', 'Justin Gatlin'], 'Usain Bolt holds the 100m and 200m world records.')
    add_q('Sports', 'medium', 'In which sport is the Vince Lombardi Trophy awarded?', 'American Football', ['Basketball', 'Baseball', 'Hockey'], 'It is awarded to the Super Bowl winner.')
    add_q('Sports', 'medium', 'How many players are on a rugby union team?', '15', ['13', '11', '7'], 'Rugby Union has 15 players.')
    add_q('Sports', 'medium', 'Which boxer was known as "Iron Mike"?', 'Mike Tyson', ['Evander Holyfield', 'Lennox Lewis', 'George Foreman'], 'Mike Tyson was nicknamed Iron Mike.')
    add_q('Sports', 'medium', 'What is the diameter of a basketball hoop?', '18 inches', ['15 inches', '20 inches', '12 inches'], 'The rim is 18 inches in diameter.')
    add_q('Sports', 'medium', 'Which country invented cricket?', 'England', ['India', 'Australia', 'South Africa'], 'Cricket originated in England.')
    add_q('Sports', 'medium', 'Who won the first Super Bowl?', 'Green Bay Packers', ['Kansas City Chiefs', 'New York Jets', 'Dallas Cowboys'], 'The Packers won Super Bowl I.')
    add_q('Sports', 'medium', 'What is the distance of a sprint triathlon swim?', '750 meters', ['1500 meters', '500 meters', '1000 meters'], 'A sprint swim is usually 750m.')
    add_q('Sports', 'medium', 'Which NBA team has the most championships?', 'Boston Celtics', ['Los Angeles Lakers', 'Chicago Bulls', 'Golden State Warriors'], 'The Celtics have 18 titles (as of 2024).')
    add_q('Sports', 'medium', 'Who is the all-time leading scorer in NBA history?', 'LeBron James', ['Kareem Abdul-Jabbar', 'Karl Malone', 'Kobe Bryant'], 'LeBron James surpassed Kareem in 2023.')
    add_q('Sports', 'medium', 'In tennis, what does "love" mean?', 'Zero', ['One', 'Tie', 'Advantage'], 'Love means a score of zero.')

    # Hard
    add_q('Sports', 'hard', 'Which year were the first modern Olympics held?', '1896', ['1900', '1892', '1904'], 'They were held in Athens in 1896.')
    add_q('Sports', 'hard', 'Who is the only athlete to play in a Super Bowl and a World Series?', 'Deion Sanders', ['Bo Jackson', 'Brian Jordan', 'Gene Conley'], 'Deion Sanders played in both.')
    add_q('Sports', 'hard', 'Which country won the first FIFA World Cup in 1930?', 'Uruguay', ['Argentina', 'Brazil', 'Italy'], 'Uruguay hosted and won the first World Cup.')
    add_q('Sports', 'hard', 'What is the maximum break in snooker?', '147', ['155', '140', '150'], 'A maximum break is 147 (without a free ball).')
    add_q('Sports', 'hard', 'Who holds the record for most Olympic gold medals?', 'Michael Phelps', ['Larisa Latynina', 'Paavo Nurmi', 'Mark Spitz'], 'Michael Phelps has 23 gold medals.')
    add_q('Sports', 'hard', 'Which horse won the Triple Crown in 1973?', 'Secretariat', ['Seattle Slew', 'Affirmed', 'American Pharoah'], 'Secretariat set records that still stand.')
    add_q('Sports', 'hard', 'Who was the first African American to play in MLB?', 'Jackie Robinson', ['Satchel Paige', 'Hank Aaron', 'Willie Mays'], 'Jackie Robinson broke the color barrier in 1947.')
    add_q('Sports', 'hard', 'Which city has hosted the Olympics three times?', 'London', ['Paris', 'Los Angeles', 'Athens'], 'London hosted in 1908, 1948, and 2012.')
    add_q('Sports', 'hard', 'What is the national sport of Canada?', 'Ice Hockey & Lacrosse', ['Ice Hockey', 'Lacrosse', 'Curling'], 'Hockey (winter) and Lacrosse (summer) are both national sports.')
    add_q('Sports', 'hard', 'Who is the only person to win a gold medal in the Summer and Winter Olympics?', 'Eddie Eagan', ['Jim Thorpe', 'Clara Hughes', 'Christa Luding-Rothenburger'], 'Eddie Eagan won in boxing (1920) and bobsled (1932).')
    add_q('Sports', 'hard', 'Which country has won the most Davis Cup titles?', 'USA', ['Australia', 'France', 'Great Britain'], 'The USA has the most titles.')
    add_q('Sports', 'hard', 'Who scored the "Hand of God" goal?', 'Diego Maradona', ['Pele', 'Lionel Messi', 'Cristiano Ronaldo'], 'Maradona scored it in the 1986 World Cup.')
    add_q('Sports', 'hard', 'What is the length of a cricket pitch?', '22 yards', ['20 yards', '24 yards', '18 yards'], 'A cricket pitch is 22 yards long.')
    add_q('Sports', 'hard', 'Which Formula 1 driver has the most World Championships?', 'Lewis Hamilton & Michael Schumacher', ['Ayrton Senna', 'Sebastian Vettel', 'Alain Prost'], 'Both have 7 titles.')
    add_q('Sports', 'hard', 'In which year was the first Tour de France held?', '1903', ['1900', '1910', '1899'], 'The first Tour de France was in 1903.')

    # ART
    # Easy
    add_q('Art', 'easy', 'Who painted the Mona Lisa?', 'Leonardo da Vinci', ['Michelangelo', 'Raphael', 'Donatello'], 'Leonardo da Vinci painted the Mona Lisa.')
    add_q('Art', 'easy', 'Who painted the Starry Night?', 'Vincent van Gogh', ['Pablo Picasso', 'Claude Monet', 'Salvador Dali'], 'Van Gogh painted Starry Night.')
    add_q('Art', 'easy', 'What is the primary color mixed with red to make orange?', 'Yellow', ['Blue', 'Green', 'Purple'], 'Red and Yellow make Orange.')
    add_q('Art', 'easy', 'Who sculpted David?', 'Michelangelo', ['Leonardo da Vinci', 'Donatello', 'Bernini'], 'Michelangelo created the statue of David.')
    add_q('Art', 'easy', 'Which artist is famous for melting clocks?', 'Salvador Dali', ['Picasso', 'Magritte', 'Warhol'], 'Dali painted "The Persistence of Memory".')
    add_q('Art', 'easy', 'What style of art is Picasso famous for?', 'Cubism', ['Impressionism', 'Surrealism', 'Realism'], 'Picasso co-founded Cubism.')
    add_q('Art', 'easy', 'Who painted the ceiling of the Sistine Chapel?', 'Michelangelo', ['Raphael', 'Leonardo', 'Botticelli'], 'Michelangelo painted the ceiling.')
    add_q('Art', 'easy', 'What is the color of a sapphire?', 'Blue', ['Red', 'Green', 'Yellow'], 'Sapphires are typically blue.')
    add_q('Art', 'easy', 'Which artist cut off his own ear?', 'Vincent van Gogh', ['Paul Gauguin', 'Claude Monet', 'Rembrandt'], 'Van Gogh famously cut off part of his ear.')
    add_q('Art', 'easy', 'Who painted "The Scream"?', 'Edvard Munch', ['Gustav Klimt', 'Egon Schiele', 'Wassily Kandinsky'], 'Edvard Munch painted The Scream.')
    add_q('Art', 'easy', 'What is the art of folding paper called?', 'Origami', ['Kirigami', 'Ikebana', 'Calligraphy'], 'Origami is the Japanese art of paper folding.')
    add_q('Art', 'easy', 'Who painted the "Girl with a Pearl Earring"?', 'Johannes Vermeer', ['Rembrandt', 'Frans Hals', 'Jan Steen'], 'Vermeer painted the masterpiece.')
    add_q('Art', 'easy', 'Which country is the Louvre Museum in?', 'France', ['Italy', 'Spain', 'UK'], 'The Louvre is in Paris, France.')
    add_q('Art', 'easy', 'What is a mural?', 'A painting on a wall', ['A sculpture', 'A sketch', 'A mosaic'], 'A mural is artwork applied directly to a wall.')
    add_q('Art', 'easy', 'Who is known for painting water lilies?', 'Claude Monet', ['Manet', 'Renoir', 'Degas'], 'Monet painted a famous series of water lilies.')

    # Medium
    add_q('Art', 'medium', 'Which movement was Claude Monet a part of?', 'Impressionism', ['Expressionism', 'Surrealism', 'Cubism'], 'Monet was a founder of Impressionism.')
    add_q('Art', 'medium', 'Who painted "The Last Supper"?', 'Leonardo da Vinci', ['Michelangelo', 'Raphael', 'Tintoretto'], 'Leonardo painted the Last Supper.')
    add_q('Art', 'medium', 'What is the technique of painting on wet plaster?', 'Fresco', ['Tempera', 'Oil', 'Watercolor'], 'Fresco is painting on wet lime plaster.')
    add_q('Art', 'medium', 'Who created the mobile sculpture?', 'Alexander Calder', ['Henry Moore', 'Alberto Giacometti', 'Auguste Rodin'], 'Calder invented the mobile.')
    add_q('Art', 'medium', 'Which artist is known for pop art soup cans?', 'Andy Warhol', ['Roy Lichtenstein', 'Keith Haring', 'Jasper Johns'], 'Warhol painted Campbell\'s Soup Cans.')
    add_q('Art', 'medium', 'Who painted "Guernica"?', 'Pablo Picasso', ['Salvador Dali', 'Joan Miro', 'Frida Kahlo'], 'Picasso painted Guernica in response to the bombing.')
    add_q('Art', 'medium', 'What is the Venus de Milo made of?', 'Marble', ['Bronze', 'Gold', 'Clay'], 'It is an ancient Greek marble statue.')
    add_q('Art', 'medium', 'Who painted "American Gothic"?', 'Grant Wood', ['Edward Hopper', 'Norman Rockwell', 'Andrew Wyeth'], 'Grant Wood painted the farmer and his daughter.')
    add_q('Art', 'medium', 'Which artist is known for dripping paint?', 'Jackson Pollock', ['Mark Rothko', 'Willem de Kooning', 'Franz Kline'], 'Pollock was a major figure in abstract expressionism.')
    add_q('Art', 'medium', 'Who painted "The Birth of Venus"?', 'Sandro Botticelli', ['Leonardo', 'Michelangelo', 'Titian'], 'Botticelli painted it in the mid-1480s.')
    add_q('Art', 'medium', 'What is the term for light and dark contrast in art?', 'Chiaroscuro', ['Sfumato', 'Impasto', 'Tenebrism'], 'Chiaroscuro is the use of strong contrasts.')
    add_q('Art', 'medium', 'Who designed the Guggenheim Museum in NYC?', 'Frank Lloyd Wright', ['Frank Gehry', 'Le Corbusier', 'I.M. Pei'], 'Frank Lloyd Wright designed the spiral building.')
    add_q('Art', 'medium', 'Which artist is famous for self-portraits with a unibrow?', 'Frida Kahlo', ['Diego Rivera', 'Georgia O\'Keeffe', 'Mary Cassatt'], 'Frida Kahlo is known for her self-portraits.')
    add_q('Art', 'medium', 'Who painted "The Night Watch"?', 'Rembrandt', ['Vermeer', 'Rubens', 'Van Dyck'], 'Rembrandt painted the militia company.')
    add_q('Art', 'medium', 'What is the primary medium of Rodin\'s "The Thinker"?', 'Bronze', ['Marble', 'Wood', 'Steel'], 'The Thinker is cast in bronze.')

    # Hard
    add_q('Art', 'hard', 'Who painted "Las Meninas"?', 'Diego Velázquez', ['Francisco Goya', 'El Greco', 'Murillo'], 'Velázquez painted the Spanish royal family.')
    add_q('Art', 'hard', 'Which art movement did Marcel Duchamp belong to?', 'Dada', ['Surrealism', 'Futurism', 'Constructivism'], 'Duchamp was associated with Dada and Surrealism.')
    add_q('Art', 'hard', 'Who painted "The Garden of Earthly Delights"?', 'Hieronymus Bosch', ['Pieter Bruegel', 'Jan van Eyck', 'Albrecht Durer'], 'Bosch painted the triptych.')
    add_q('Art', 'hard', 'What is the name of the technique using dots of color?', 'Pointillism', ['Divisionism', 'Impressionism', 'Fauvism'], 'Georges Seurat developed Pointillism.')
    add_q('Art', 'hard', 'Who painted "The School of Athens"?', 'Raphael', ['Michelangelo', 'Leonardo', 'Donatello'], 'Raphael painted the fresco in the Vatican.')
    add_q('Art', 'hard', 'Which artist created the "Balloon Dog" sculptures?', 'Jeff Koons', ['Damien Hirst', 'Takashi Murakami', 'Banksy'], 'Jeff Koons is known for his balloon animals.')
    add_q('Art', 'hard', 'Who painted "Nighthawks"?', 'Edward Hopper', ['Grant Wood', 'Thomas Hart Benton', 'Norman Rockwell'], 'Hopper painted the late-night diner scene.')
    add_q('Art', 'hard', 'What is the name of the art school founded by Gropius?', 'Bauhaus', ['De Stijl', 'Art Deco', 'Art Nouveau'], 'The Bauhaus school was influential in design.')
    add_q('Art', 'hard', 'Who painted "Liberty Leading the People"?', 'Eugène Delacroix', ['Théodore Géricault', 'Jacques-Louis David', 'Ingres'], 'Delacroix commemorated the July Revolution.')
    add_q('Art', 'hard', 'Which artist is known for his "Black Paintings"?', 'Francisco Goya', ['Velázquez', 'El Greco', 'Zurbarán'], 'Goya painted them late in his life.')
    add_q('Art', 'hard', 'Who created the "Spiral Jetty"?', 'Robert Smithson', ['Andy Goldsworthy', 'Christo', 'Richard Long'], 'Smithson created the earthwork sculpture.')
    add_q('Art', 'hard', 'Which artist was a rival of Bernini?', 'Francesco Borromini', ['Caravaggio', 'Canova', 'Donatello'], 'Borromini was a rival architect in Rome.')
    add_q('Art', 'hard', 'Who painted "The Raft of the Medusa"?', 'Théodore Géricault', ['Delacroix', 'David', 'Courbet'], 'Géricault depicted the shipwreck survivors.')
    add_q('Art', 'hard', 'What is the term for painting outdoors?', 'En plein air', ['Alla prima', 'Impasto', 'Grisaille'], 'En plein air means in the open air.')
    add_q('Art', 'hard', 'Who painted "The Arnolfini Portrait"?', 'Jan van Eyck', ['Rogier van der Weyden', 'Hans Memling', 'Bosch'], 'Jan van Eyck painted the wedding portrait.')

    # ENTERTAINMENT: FILM
    # Easy
    add_q('Entertainment: Film', 'easy', 'Who played Jack in "Titanic"?', 'Leonardo DiCaprio', ['Brad Pitt', 'Tom Cruise', 'Johnny Depp'], 'Leonardo DiCaprio starred as Jack Dawson.')
    add_q('Entertainment: Film', 'easy', 'What is the name of the toy cowboy in "Toy Story"?', 'Woody', ['Buzz', 'Rex', 'Hamm'], 'Woody is the cowboy doll.')
    add_q('Entertainment: Film', 'easy', 'Which movie features a character named Darth Vader?', 'Star Wars', ['Star Trek', 'Alien', 'Avatar'], 'Darth Vader is the villain in Star Wars.')
    add_q('Entertainment: Film', 'easy', 'Who is the voice of Dory in "Finding Nemo"?', 'Ellen DeGeneres', ['Whoopi Goldberg', 'Tina Fey', 'Amy Poehler'], 'Ellen DeGeneres voiced Dory.')
    add_q('Entertainment: Film', 'easy', 'What kind of animal is Baloo in "The Jungle Book"?', 'Bear', ['Tiger', 'Wolf', 'Snake'], 'Baloo is a bear.')
    add_q('Entertainment: Film', 'easy', 'Which movie features the song "Let It Go"?', 'Frozen', ['Moana', 'Tangled', 'Brave'], 'Frozen features the hit song.')
    add_q('Entertainment: Film', 'easy', 'Who played Iron Man in the MCU?', 'Robert Downey Jr.', ['Chris Evans', 'Chris Hemsworth', 'Mark Ruffalo'], 'RDJ played Tony Stark/Iron Man.')
    add_q('Entertainment: Film', 'easy', 'What is the name of the ogre in "Shrek"?', 'Shrek', ['Donkey', 'Fiona', 'Farquaad'], 'The main character is Shrek.')
    add_q('Entertainment: Film', 'easy', 'Which movie is set in a dinosaur park?', 'Jurassic Park', ['King Kong', 'Godzilla', 'Jaws'], 'Jurassic Park features cloned dinosaurs.')
    add_q('Entertainment: Film', 'easy', 'Who played Harry Potter?', 'Daniel Radcliffe', ['Rupert Grint', 'Tom Felton', 'Elijah Wood'], 'Daniel Radcliffe played the title character.')
    add_q('Entertainment: Film', 'easy', 'What is the name of the lion king?', 'Simba', ['Mufasa', 'Scar', 'Nala'], 'Simba becomes the Lion King.')
    add_q('Entertainment: Film', 'easy', 'Which movie features a shark?', 'Jaws', ['E.T.', 'Close Encounters', 'Indiana Jones'], 'Jaws is a famous shark movie.')
    add_q('Entertainment: Film', 'easy', 'Who is the captain of the Black Pearl?', 'Jack Sparrow', ['Will Turner', 'Barbossa', 'Davy Jones'], 'Captain Jack Sparrow commands the ship.')
    add_q('Entertainment: Film', 'easy', 'What color is the pill Neo takes in "The Matrix"?', 'Red', ['Blue', 'Green', 'Yellow'], 'Neo takes the red pill to see the truth.')
    add_q('Entertainment: Film', 'easy', 'Who played the Joker in "The Dark Knight"?', 'Heath Ledger', ['Jack Nicholson', 'Jared Leto', 'Joaquin Phoenix'], 'Heath Ledger gave a legendary performance.')

    # Medium
    add_q('Entertainment: Film', 'medium', 'Who directed "Avatar"?', 'James Cameron', ['Steven Spielberg', 'George Lucas', 'Christopher Nolan'], 'James Cameron directed the 2009 blockbuster.')
    add_q('Entertainment: Film', 'medium', 'Which movie won the first Oscar for Best Animated Feature?', 'Shrek', ['Toy Story', 'Monsters, Inc.', 'Finding Nemo'], 'Shrek won the inaugural award in 2001.')
    add_q('Entertainment: Film', 'medium', 'Who played Forrest Gump?', 'Tom Hanks', ['Robin Williams', 'Harrison Ford', 'Kevin Costner'], 'Tom Hanks won an Oscar for the role.')
    add_q('Entertainment: Film', 'medium', 'What is the highest-grossing movie of all time (as of 2024)?', 'Avatar', ['Avengers: Endgame', 'Titanic', 'Star Wars: The Force Awakens'], 'Avatar holds the record.')
    add_q('Entertainment: Film', 'medium', 'Who directed "Pulp Fiction"?', 'Quentin Tarantino', ['Martin Scorsese', 'Francis Ford Coppola', 'Stanley Kubrick'], 'Tarantino directed the cult classic.')
    add_q('Entertainment: Film', 'medium', 'Which movie features the quote "Here\'s looking at you, kid"?', 'Casablanca', ['Gone with the Wind', 'Citizen Kane', 'The Godfather'], 'Humphrey Bogart says it in Casablanca.')
    add_q('Entertainment: Film', 'medium', 'Who played Wolverine in the X-Men movies?', 'Hugh Jackman', ['Patrick Stewart', 'Ian McKellen', 'Ryan Reynolds'], 'Hugh Jackman played Wolverine.')
    add_q('Entertainment: Film', 'medium', 'What is the name of the hobbit played by Elijah Wood?', 'Frodo Baggins', ['Samwise Gamgee', 'Bilbo Baggins', 'Pippin Took'], 'Frodo is the ring-bearer.')
    add_q('Entertainment: Film', 'medium', 'Which movie features a character named Hannibal Lecter?', 'The Silence of the Lambs', ['Se7en', 'Psycho', 'Halloween'], 'Anthony Hopkins played Hannibal.')
    add_q('Entertainment: Film', 'medium', 'Who directed "E.T."?', 'Steven Spielberg', ['George Lucas', 'Ridley Scott', 'James Cameron'], 'Spielberg directed the sci-fi hit.')
    add_q('Entertainment: Film', 'medium', 'What is the name of the fictional country in "Black Panther"?', 'Wakanda', ['Zamunda', 'Genovia', 'Latveria'], 'Wakanda is the home of Black Panther.')
    add_q('Entertainment: Film', 'medium', 'Who played the Terminator?', 'Arnold Schwarzenegger', ['Sylvester Stallone', 'Jean-Claude Van Damme', 'Bruce Willis'], 'Schwarzenegger is the Terminator.')
    add_q('Entertainment: Film', 'medium', 'Which movie features the DeLorean time machine?', 'Back to the Future', ['Blade Runner', 'Total Recall', 'The Terminator'], 'The DeLorean is iconic to the franchise.')
    add_q('Entertainment: Film', 'medium', 'Who directed "The Godfather"?', 'Francis Ford Coppola', ['Martin Scorsese', 'Sergio Leone', 'Brian De Palma'], 'Coppola directed the trilogy.')
    add_q('Entertainment: Film', 'medium', 'What is the name of the hotel in "The Shining"?', 'Overlook Hotel', ['Bates Motel', 'Grand Budapest Hotel', 'Plaza Hotel'], 'The Overlook Hotel is the setting.')

    # Hard
    add_q('Entertainment: Film', 'hard', 'Who won the first Best Actor Oscar?', 'Emil Jannings', ['Charlie Chaplin', 'Clark Gable', 'Spencer Tracy'], 'Emil Jannings won in 1929.')
    add_q('Entertainment: Film', 'hard', 'Which movie was the first to use CGI for a main character?', 'Young Sherlock Holmes', ['Tron', 'The Abyss', 'Terminator 2'], 'The stained glass knight in Young Sherlock Holmes (1985) is often cited.')
    add_q('Entertainment: Film', 'hard', 'Who directed "Citizen Kane"?', 'Orson Welles', ['Alfred Hitchcock', 'John Ford', 'Billy Wilder'], 'Orson Welles directed and starred in it.')
    add_q('Entertainment: Film', 'hard', 'What is the name of the sled in "Citizen Kane"?', 'Rosebud', ['Snowbud', 'Flower', 'Sleigh'], 'Rosebud is the dying word.')
    add_q('Entertainment: Film', 'hard', 'Which movie won 11 Oscars (tied for most)?', 'Ben-Hur, Titanic, LOTR: Return of the King', ['Gone with the Wind', 'Star Wars', 'La La Land'], 'All three films won 11 Academy Awards.')
    add_q('Entertainment: Film', 'hard', 'Who played the lead in "Lawrence of Arabia"?', 'Peter O\'Toole', ['Alec Guinness', 'Omar Sharif', 'Anthony Quinn'], 'Peter O\'Toole played T.E. Lawrence.')
    add_q('Entertainment: Film', 'hard', 'Which movie features the "Odessa Steps" sequence?', 'Battleship Potemkin', ['October', 'Strike', 'Mother'], 'Eisenstein\'s Battleship Potemkin is famous for the montage.')
    add_q('Entertainment: Film', 'hard', 'Who directed "2001: A Space Odyssey"?', 'Stanley Kubrick', ['Arthur C. Clarke', 'Ridley Scott', 'George Lucas'], 'Kubrick directed the sci-fi masterpiece.')
    add_q('Entertainment: Film', 'hard', 'What is the name of the computer in "2001: A Space Odyssey"?', 'HAL 9000', ['IBM', 'Skynet', 'Mother'], 'HAL 9000 is the antagonist.')
    add_q('Entertainment: Film', 'hard', 'Which movie was the first talkie?', 'The Jazz Singer', ['Singin\' in the Rain', 'Metropolis', 'Sunrise'], 'The Jazz Singer (1927) was the first feature-length talkie.')
    add_q('Entertainment: Film', 'hard', 'Who played the Wicked Witch of the West?', 'Margaret Hamilton', ['Judy Garland', 'Billie Burke', 'Ray Bolger'], 'Margaret Hamilton played the iconic villain.')
    add_q('Entertainment: Film', 'hard', 'Which Hitchcock movie appears to be one continuous shot?', 'Rope', ['Vertigo', 'Rear Window', 'Psycho'], 'Rope (1948) was edited to look like one shot.')
    add_q('Entertainment: Film', 'hard', 'Who directed "Seven Samurai"?', 'Akira Kurosawa', ['Yasujiro Ozu', 'Kenji Mizoguchi', 'Hayao Miyazaki'], 'Kurosawa directed the samurai epic.')
    add_q('Entertainment: Film', 'hard', 'What is the name of the planet in "Alien"?', 'LV-426', ['Tatooine', 'Arrakis', 'Pandora'], 'The crew lands on LV-426.')
    add_q('Entertainment: Film', 'hard', 'Who played the lead in "The Graduate"?', 'Dustin Hoffman', ['Robert Redford', 'Warren Beatty', 'Jack Nicholson'], 'Dustin Hoffman played Benjamin Braddock.')

    # Write to file
    with open('/Users/seleemaleshinloye/quiz-app/quiz_app/lib/screens/generated_questions.dart', 'w') as f:
        f.write("import '../models/question_model.dart';\n\n")
        f.write("final List<Map<String, dynamic>> generatedQuestions = [\n")
        
        for q in questions:
            f.write("  {\n")
            f.write(f"    'category': '{q['category']}',\n")
            f.write(f"    'difficulty': '{q['difficulty']}',\n")
            # Escape single quotes and backslashes in strings
            question_escaped = q['question'].replace("\\", "\\\\").replace("'", "\\'")
            answer_escaped = q['correct_answer'].replace("\\", "\\\\").replace("'", "\\'")
            explanation_escaped = q['explanation'].replace("\\", "\\\\").replace("'", "\\'")
            
            f.write(f"    'question': '{question_escaped}',\n")
            f.write(f"    'correct_answer': '{answer_escaped}',\n")
            
            # Handle incorrect_answers list
            f.write("    'incorrect_answers': [")
            escaped_incorrect = [ans.replace("\\", "\\\\").replace("'", "\\'") for ans in q['incorrect_answers']]
            f.write(", ".join([f"'{ans}'" for ans in escaped_incorrect]))
            f.write("],\n")
            
            f.write(f"    'explanation': '{explanation_escaped}',\n")
            f.write(f"    'type': '{q['type']}',\n")
            f.write("  },\n")
        
        f.write("];\n")

if __name__ == "__main__":
    generate_questions()
