// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzi23JglDFSmKO5_62OOlJY0zF69HhmkY',
    appId: '1:362153618720:web:0458ba896bae0aed187b45',
    messagingSenderId: '362153618720',
    projectId: 'quiz-d1427',
    authDomain: 'quiz-d1427.firebaseapp.com',
    storageBucket: 'quiz-d1427.firebasestorage.app',
    measurementId: 'G-VNG6177ZVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4HQYLPat23OCGH0F_Jc6ebSnghBpxbBA',
    appId: '1:362153618720:android:c51696c7374fcb4a187b45',
    messagingSenderId: '362153618720',
    projectId: 'quiz-d1427',
    storageBucket: 'quiz-d1427.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAimeeqbmW9qJwyD7ycCXbRnaRQ7j4BRfU',
    appId: '1:362153618720:ios:1675fd0782ef57df187b45',
    messagingSenderId: '362153618720',
    projectId: 'quiz-d1427',
    storageBucket: 'quiz-d1427.firebasestorage.app',
    iosClientId: '362153618720-qod5e15ubgq7v3urkqnc7r2aou7ovb25.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAimeeqbmW9qJwyD7ycCXbRnaRQ7j4BRfU',
    appId: '1:362153618720:ios:1675fd0782ef57df187b45',
    messagingSenderId: '362153618720',
    projectId: 'quiz-d1427',
    storageBucket: 'quiz-d1427.firebasestorage.app',
    iosClientId: '362153618720-qod5e15ubgq7v3urkqnc7r2aou7ovb25.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzi23JglDFSmKO5_62OOlJY0zF69HhmkY',
    appId: '1:362153618720:web:70c9ea554498fa83187b45',
    messagingSenderId: '362153618720',
    projectId: 'quiz-d1427',
    authDomain: 'quiz-d1427.firebaseapp.com',
    storageBucket: 'quiz-d1427.firebasestorage.app',
    measurementId: 'G-Z9J0BRF9LY',
  );
}
