import 'dart:io';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:intl/intl.dart';
import 'package:open_filex/open_filex.dart';
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';

class DocxService {
  static Future<void> generateResultsDocx({
    required String className,
    required String quizTitle,
    required List<Map<String, dynamic>> results,
    Rect? sharePositionOrigin,
  }) async {
    try {
      // Build an HTML representation that Word can open as a document
      final sb = StringBuffer();
      sb.write('<html><head><meta charset="utf-8"><style>');
      sb.write(
          'body { font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif; }');
      sb.write('h1 { color: #2E3192; }');
      sb.write(
          'table { width: 100%; border-collapse: collapse; margin-top: 20px; }');
      sb.write(
          'th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }');
      sb.write('th { background-color: #f2f2f2; font-weight: bold; }');
      sb.write('tr:nth-child(even) { background-color: #fafafa; }');
      sb.write('</style></head><body>');

      sb.write('<h1>Exam Results Report: $className</h1>');
      sb.write('<h2>Quiz: $quizTitle</h2>');
      sb.write(
          '<p>Generated on: ${DateFormat.yMMMd().add_jm().format(DateTime.now())}</p>');

      sb.write('<table>');
      sb.write(
          '<thead><tr><th>Rank</th><th>Student Name</th><th>Matric Number</th><th>Score</th><th>Percentage</th></tr></thead>');
      sb.write('<tbody>');

      for (int i = 0; i < results.length; i++) {
        final result = results[i];
        final name = result['userName'] ?? 'N/A';
        final matric = result['matricNumber'] ?? 'N/A';
        final score = result['score'] ?? 0;
        final total = result['totalQuestions'] ?? 0;
        final percentage = result['percentage']?.toStringAsFixed(1) ?? '0.0';

        sb.write('<tr>');
        sb.write('<td>${i + 1}</td>');
        sb.write('<td>$name</td>');
        sb.write('<td>$matric</td>');
        sb.write('<td>$score / $total</td>');
        sb.write('<td>$percentage%</td>');
        sb.write('</tr>');
      }

      sb.write('</tbody></table>');
      sb.write(
          '<p style="margin-top: 40px; font-size: 10px; color: grey;">Generated by Mindly Quiz App</p>');
      sb.write('</body></html>');

      final directory = await getApplicationDocumentsDirectory();
      // Using .doc extension (Word opens this as HTML-based document perfectly)
      final fileName = 'Results_${className.replaceAll(' ', '_')}.doc';
      final file = File('${directory.path}/$fileName');

      await file.writeAsString(sb.toString());

      // Open or share the file
      if (!kIsWeb) {
        await OpenFilex.open(file.path);

        // Also provide share option
        await Share.shareXFiles(
          [XFile(file.path)],
          subject: 'Exam Results - $className',
          sharePositionOrigin: sharePositionOrigin,
        );
      }
    } catch (e) {
      debugPrint('Error generating Word doc: $e');
      rethrow;
    }
  }
}
