import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';

class PdfService {
  static Future<void> generateResultsPdf({
    required String className,
    required String quizTitle,
    required List<Map<String, dynamic>> results,
  }) async {
    // Load Unicode-capable fonts (essential for names or special characters)
    final fontRegular = await PdfGoogleFonts.robotoRegular();
    final fontBold = await PdfGoogleFonts.robotoBold();

    final pdf = pw.Document();

    // Standard styling with Unicode fonts
    final headerStyle = pw.TextStyle(
      font: fontBold,
      fontSize: 18,
    );
    final subHeaderStyle = pw.TextStyle(
      font: fontRegular,
      fontSize: 14,
      color: PdfColors.grey700,
    );
    final tableHeaderStyle = pw.TextStyle(
      font: fontBold,
      color: PdfColors.white,
    );
    final cellStyle = pw.TextStyle(
      font: fontRegular,
    );

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        header: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text('Exam Results Report', style: headerStyle),
              pw.SizedBox(height: 8),
              pw.Text('Class: $className', style: subHeaderStyle),
              pw.Text('Quiz: $quizTitle', style: subHeaderStyle),
              pw.Text(
                'Date: ${DateFormat.yMMMd().add_jm().format(DateTime.now())}',
                style: subHeaderStyle,
              ),
              pw.Divider(thickness: 2, color: PdfColors.blueAccent),
              pw.SizedBox(height: 10),
            ],
          );
        },
        footer: (pw.Context context) {
          return pw.Container(
            alignment: pw.Alignment.centerRight,
            margin: const pw.EdgeInsets.only(top: 10),
            child: pw.Text(
              'Page ${context.pageNumber} of ${context.pagesCount} - Generated by Mindly Quiz App',
              style: pw.TextStyle(
                font: fontRegular,
                fontSize: 10,
                color: PdfColors.grey500,
              ),
            ),
          );
        },
        build: (pw.Context context) {
          return [
            pw.SizedBox(height: 10),
            // Results Table
            pw.Table(
              border: pw.TableBorder.all(color: PdfColors.grey400, width: 0.5),
              columnWidths: {
                0: const pw.FlexColumnWidth(1), // S/N
                1: const pw.FlexColumnWidth(4), // Name
                2: const pw.FlexColumnWidth(3), // Matric No
                3: const pw.FlexColumnWidth(2), // Score
                4: const pw.FlexColumnWidth(2), // %
              },
              children: [
                // Table Header
                pw.TableRow(
                  decoration: const pw.BoxDecoration(color: PdfColors.blue800),
                  children: [
                    _buildTableCell('S/N', style: tableHeaderStyle),
                    _buildTableCell('Student Name', style: tableHeaderStyle),
                    _buildTableCell('Matric Number', style: tableHeaderStyle),
                    _buildTableCell('Score', style: tableHeaderStyle),
                    _buildTableCell('Percentage', style: tableHeaderStyle),
                  ],
                ),
                // Table Rows
                ...results.asMap().entries.map((entry) {
                  final index = entry.key;
                  final res = entry.value;
                  final isEven = index % 2 == 1;

                  return pw.TableRow(
                    decoration: pw.BoxDecoration(
                      color: isEven ? PdfColors.grey100 : PdfColors.white,
                    ),
                    children: [
                      _buildTableCell('${index + 1}', style: cellStyle),
                      _buildTableCell(res['userName'] ?? 'Unknown',
                          style: cellStyle),
                      _buildTableCell(res['matricNumber'] ?? 'N/A',
                          style: cellStyle),
                      _buildTableCell(
                          '${res['score']}/${res['totalQuestions']}',
                          style: cellStyle),
                      _buildTableCell(
                          '${(res['percentage'] as num).toStringAsFixed(1)}%',
                          style: cellStyle),
                    ],
                  );
                }),
              ],
            ),
          ];
        },
      ),
    );

    // Save PDF to bytes FIRST outside the layout callback to prevent threading issues
    final pdfBytes = await pdf.save();

    // Now layout the pre-generated bytes
    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdfBytes,
      name: '${className.replaceAll(' ', '_')}_Results.pdf',
    );
  }

  static pw.Widget _buildTableCell(String text, {pw.TextStyle? style}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(8),
      child: pw.Text(text, style: style),
    );
  }
}
